### ISSUE TITLE
SSL certificate issue when running experiment

### ISSUE THREAD

**Issue by angoodkind** [hawkrobe/tangrams#12]
When I try to launch `tangrams_sequential`, I receive the error below. I have previously run `npm install` in the `experiments/` directory.

```
(base) ➜  experiments git:(master) ✗ node app.js tangrams_sequential
cannot find SSL certificates; falling back to http
/Users/adamg/OneDrive - Northwestern University/Northwestern/Dissertation/Experiments/tangrams/experiments/sharedUtils/sharedUtils.js:155
  hsl2lab : hsl2lab,
            ^

ReferenceError: hsl2lab is not defined
    at Object.<anonymous> (/Users/adamg/OneDrive - Northwestern University/Northwestern/Dissertation/Experiments/tangrams/experiments/sharedUtils/sharedUtils.js:155:13)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/adamg/OneDrive - Northwestern University/Northwestern/Dissertation/Experiments/tangrams/experiments/sharedUtils/serverBase.js:1:75)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
```

**Comment by angoodkind** [comment]
In `sharedUtils.js`, both `hsl2lab` and `colorDiff` are not defined, but used in `module.export`. When I comment out the app runs, but I'm not sure it's running correctly. For instance, I do not see a waiting room, and in both tabs that I load it, it says I'm the director, whereas when I type a message it says I'm the matcher. I cannot select a picture though.

**Comment by hawkrobe** [comment]
thanks for letting me know -- I'll take a look!

**Comment by hawkrobe** [comment]
I just pushed a fix -- please pull the latest version and let me know if it works for you now!

**Comment by angoodkind** [comment]
That took care of it. Thanks!

Just FYI, in the README file for `experiments`, in 3. you may want to mention that `npm install` needs to be run in the `experiments/` directory.
